anvilistas/anvil-labs

client_code/atomic/decorators.py
client_code/atomic/subscribers.py

atomic: actually return the wrapped function results and tweak a name

---

client_code/atomic/subscribers.py

I wanted to be able to force a render when using a form in an alert
the render method was too late because alerts animate in

add a force render option

---

client_code/atomic/atoms.py

atomic: make sure we only ever create a single Registrar

---

.github/workflows/check_codebase.yml
client_code/pedantic.py
setup.cfg
tests/test_pedantic.py

Module to add validation to client side classes

Pedantic Module

---

client_code/exceptions.py
client_code/historic/__init__.py
client_code/historic/exceptions.py
client_code/historic/model.py
server_code/historic_server/__init__.py
server_code/historic_server/persistence.py
server_code/historic_server/projection.py
server_code/historic_server/projectors/__init__.py
server_code/historic_server/projectors/current.py
tests/test_historic.py

This is a rewrite of the observation module. It's still very much WIP, but I'll happily take whatever comments come my way!
Note - it's built on top the pedantic branch.
Unit testing app for this:
https://anvil.works/build#clone:JS6Y46WUIZ2YHL2E=MLRVLC5GXKTQ5EYWMZQ26W2M

Historic Module

---

client_code/atomic/atoms.py

This should fix the bug in the example you were working on @meatballs 
tested locally and works for me.

add support for dict views to be depended on

---

client_code/atomic/atoms.py
client_code/atomic/constants.py

This should give atoms the ability to be portable classes

atoms can be portable classes

---

client_code/atomic/atoms.py

atomic - make a portable atom an actual atom!

---

client_code/atomic/atoms.py

Add __deserialize__ method to portable atoms

---

client_code/atomic/__init__.py
client_code/atomic/decorators.py
docs/guides/modules/atomic.rst
tests/test_atomic.py

atomic: add tests, include unsubscribe, and make autorun a decorator

---

client_code/atomic/contexts.py
client_code/atomic/decorators.py
client_code/atomic/rendering.py
client_code/atomic/subscribers.py
docs/guides/modules/atomic.rst
tests/test_atomic.py

I think the autorun should also return a dispose of method - like reaction.
Which makes me thing maybe a subscriber should also return the dispose of method??
added some comments, docs and tests too.

atomic: tweaks

---

client_code/atomic/atoms.py

I think this hack is better than the serialize hack
When we get slots we can remove this hack
_(I also changed the name of `__derserialize__` because it was nicer in the debug log)_

override dunder dict while skulpt doesn't have slots

---

client_code/atomic/atoms.py
tests/test_atomic.py

Atomic - fix __dict__ for subclasses

---

server_code/historic_server/__init__.py
server_code/historic_server/persistence.py

Replace prevent_duplication with record_duplicates

---

server_code/historic_server/persistence.py
server_code/historic_server/projection.py

@jshaffstall 
hopefully this stops the initial roadblock
merging as a bug

fix bad logger import

---

client_code/kompot/__init__.py
client_code/kompot/_batcher.py
client_code/kompot/_rpc.py
docs/guides/modules/kompot.rst

just an idea - based on #64 
close #64

implement batch_call idea

---

client_code/non_blocking.py
docs/guides/modules/non_blocking.rst

non-blocking: working timer api idea

---

client_code/historic/services.py

Ties atomic and historic modules together.
Based on https://github.com/anvilistas/demo-mvc-atomic/blob/main/client_code/controllers.py
but with a few improvements having used it for real!

Add archivist class to historic

---

.gitignore
client_code/web_worker.py
docs/guides/modules/web_worker.rst
js/web-worker/bg-worker.ts
js/web-worker/build-script.ts
js/web-worker/make-script.ts
js/web-worker/mod.ts
js/web-worker/rsvp_types.d.ts
js/web-worker/types.ts
js/web-worker/web-worker.ts
tsconfig.json

very experimental
but works fairly well locally
I wrote the web workers in typescript
then minified them and injected them into the python script
when the user wants to use the web worker module the javascript gets injected into the page as required.

Web worker

---

client_code/kompot/_rpc.py
server_code/historic_server/persistence.py

Will undraft when these Errors are exposed in anvil production

Catch newly exposed server errors

---

client_code/dataklasses.py

inspired by https://anvil.works/forum/t/simplifying-class-construction-dave-beazleys-dataklass-module/14329
because skulpt doesn't expose the `__code__` object, don't use the caching techniques on the client
on the server only works in the 3.10 beta

dataklasses - adjust david beazley's code for anvil/skulpt

---

client_code/cluegen.py

Less adjustement required than for dataklasses
Since we now have `init_subclass` and `set_name` this just works
see original library: https://github.com/dabeaz/cluegen

cluegen: implement cluegen because why not

---

anvil.yaml
client_code/service_worker.py

this was fixed in anvil proper

service-worker: remove temporary hack

---

docs/guides/modules/web_worker.rst

Adjust example code so the button click runs.
close #142

Update web_worker.rst example code

---

client_code/atomic/atoms.py

fix sort takes kws
